Resources:
  myCustRole0:
    Type: AWS::IAM::Role
    Properties:
      Path: /my/cust/path/
      RoleName: MyCustRole0
      AssumeRolePolicyDocument:
        Version: '2017'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: myPolicyName
          PolicyDocument:
            Version: '2017'
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"